<div class="row">

	<?php
	//Do Result notifications
	foreach ($this->notifications as $notification) {
		if ($notification['type'] == 'success') {
			echo "<div id='notifygood'>";
			echo $notification['text'];
			echo "</div>";
		} else {
			echo "<div id='notifybad'>";
			echo $notification['text'];
			echo "</div>";
		}
	}
	//Auto set our next bib
		print_r($this -> postData);
	if (($this -> postData)) {
		$bibVal = ($this -> postData[0]['bibnumber'] + 1);
	} else {
		$bibVal = "";
	}
	?>

	<!-- set value for our bib field -->
	<script type="text/javascript">
		$(document).ready(function() {
		$('#bibnumber').val(<?=$bibVal?>
		);
		});
	</script>

	<form id="insertForm" action="/insert/post" method="post">
		<h2>Main Entry Form</h2>

		<div class="formRow">
			<div class="formcol1">
				<h3>Bib Number:</h3>
			</div>
			<div class="formcol2">

				<input id="bibnumber" name="bibnumber" type="text" size="10" maxlength="4">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Last Name:</h3>
			</div>
			<div class="formcol2">
				<input id="lastname" name="lastname" type="text" size="25">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>First Name:</h3>
			</div>
			<div class="formcol2">
				<input id="firstname" name="firstname" type="text" size="25">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Address1:</h3>
			</div>
			<div class="formcol2">
				<input id="address1" name="address1" type="text" size="55">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Address2:</h3>
			</div>
			<div class="formcol2">
				<input id="address2" name="address2" type="text" size="55">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Zip Code:</h3>
			</div>
			<div class="formcol2">
				<input id="zipcode" name="zipcode" type="text" size="10" maxlength="5">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>City:</h3>
			</div>
			<div class="formcol2">
				<input id="city" name="city" type="text" size="40">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>State:</h3>
			</div>
			<div class="formcol2">
				<input id="state" name="state" type="text" size="15" maxlength="2">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Email:</h3>
			</div>
			<div class="formcol2">
				<input name="email" type="text" size="55">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Age:</h3>
			</div>
			<div class="formcol2">
				<input name="age" type="text" size="4" maxlength="2">
			</div>
		</div>

		<div class="formRow">
			<div class="formcol1">
				<h3>Gender:</h3>
			</div>
			<div class="formcol2">
				<ul id="radiolist" class="clearfix">
					<li>
						<input name="sex" type="radio" value="M" id="M"checked>
						Male
					</li>
					<li>
						<input name="sex" type="radio" value="F" id="F">
						Female
					</li>
					<li>
						<input name="sex" type="radio" value="X" id="X">
						Other
					</li>
				</ul>
			</div>
		</div>

		<div class="formRow">
			<div class="formcol1">
				<h3>T-Shirt Size:</h3>
			</div>
			<div class="formcol2">
				<?php
				echo $this -> partial('partials/shirtRadios.phtml', array('result' => $this -> sizeOptions));
				?>
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Event:</h3>
			</div>
			<div class="formcol2">
				<?php
				echo $this -> partial('partials/eventRadios.phtml', array('result' => $this -> eventOptions));
				?>
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Division:</h3>
			</div>
			<div class="formcol2">
				<?php
				echo $this -> partial('partials/divisionRadios.phtml', array('result' => $this -> divisionOptions));
				?>
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Team Name:</h3>
			</div>
			<div class="formcol2">
				<input name="team" type="text" size="40">
			</div>
		</div>
		<div class="formRow">
			<div class="formcol1">
				<h3>Registration Type:</h3>
			</div>
			<div class="formcol2">
				<?php
				echo $this -> partial('partials/registrationRadios.phtml', array('result' => $this -> registrationOptions));
				?>
			</div>
		</div>
		<input class="button" type="submit" value="Submit" name="submit">

</div>
