<div class="row">
	<div id="stats">
	<div id='notifyfact'>
		<div id="statsHeader">TotalParticiants:</div>  <div id="statsData"><?=$this -> totalParticipants ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Male:</div> <div id="statsData"><?=$this -> totalMale ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Female:</div> <div id="statsData"><?=$this -> totalFemale ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Ten K:</div> <div id="statsData"><?=$this -> totalTenk ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Five K:</div> <div id="statsData"><?=$this -> totalFivek ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Half Marathon:</div> <div id="statsData"><?=$this -> totalHalf ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total DoubleHeader:</div> <div id="statsData"><?=$this -> totalDouble ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Wheelchair:</div> <div id="statsData"><?=$this -> totalWheel ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Age 0-12:</div> <div id="statsData"><?=$this -> totalAge1 ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Age 13-17:</div><div id="statsData"><?=$this -> totalAge2 ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Age 18-24:</div><div id="statsData"><?=$this -> totalAge3 ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Age 25-34:</div><div id="statsData"><?=$this -> totalAge4 ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Age 35-44:</div><div id="statsData"><?=$this -> totalAge5 ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Age 45-59:</div><div id="statsData"><?=$this -> totalAge6 ?></div>
	</div>
	<div id='notifyfact'>
		<div id="statsHeader">Total Age 60+:</div><div id="statsData"><?=$this -> totalAge7 ?></div>
	</div>
	</div>
